name: "Release Beta - Unlocked"
description: "Upload a Unlocked beta package version"
inputs:
  cumulusci-version:
    description: 'version of CumulusCI to install'
    required: false
  sf-version:
    description: 'version of sf to install'
    required: false
  dev-hub-auth-url:
    description: 'sf auth URL for the Dev Hub'
    required: true
  org-name:
    description: 'Name of the scratch org config to use'
    required: true
    default: release
runs:
  using: "composite"
  steps:
      - uses: MyClubHub/cumulusci-run-flow-scratch@v4
        with:
          dev-hub-auth-url: '${{ inputs.dev-hub-auth-url }}'
          org-name: '${{ inputs.org-name }}'
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sf-version: '${{ inputs.sf-version }}'
          flow-name: release_unlocked_beta
